# This is a composition of lint and test scripts
# Make sure to update this file along with the others

name: Test and Release

# Run this job on all pushes and pull requests
# as well as tags with a semantic version
on:
  push:
    branches:
      - '*'
    tags:
      # normal versions
      - "v?[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v?[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: {}

jobs:
  # Performs quick checks before the expensive test runs
  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install Dependencies
        run: npm ci

#      - name: Perform a type check
#        run: npm run check:ts
#        env:
#          CI: true
      # - name: Lint TypeScript code
      #   run: npm run lint
#      - name: Test package files
#        run: npm run test:package

  # Runs adapter tests on all supported node versions and OSes
  adapter-tests-influxdb1:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    needs: [check-and-lint]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Install Influxdb 1.x (Linux)
        if: startsWith(runner.OS, 'linux')
        run: |
          wget -nv https://dl.influxdata.com/influxdb/releases/influxdb_1.8.6_amd64.deb
          sudo dpkg -i influxdb_1.8.6_amd64.deb
          sudo systemctl start influxdb

      - name: Run local tests (Linux)
        if: startsWith(runner.OS, 'linux')
        run: npm test
#      - name: Run unit tests
#        run: npm run test:unit
#      - name: Run integration tests # (linux/osx)
#        if: startsWith(runner.OS, 'windows') == false
#        run: DEBUG=testing:* npm run test:integration
#      - name: Run integration tests # (windows)
#        if: startsWith(runner.OS, 'windows')
#        run: set DEBUG=testing:* & npm run test:integration

  # Runs adapter tests on all supported node versions and OSes
  adapter-tests-influxdb2:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    needs: [check-and-lint]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Install Influxdb 2.x (Linux)
        id: influxdb2
        if: startsWith(runner.OS, 'linux')
        run: |
          wget -nv https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.7-amd64.deb
          sudo dpkg -i influxdb2-2.0.7-amd64.deb
          sudo systemctl start influxdb
          sleep 20
          sudo journalctl -u influxdb
          sudo influx setup --org test-org --bucket test-bucket --username test-user --password test-password --token test-token --force
          sudo influx config list
          AUTHTOKEN=$(sudo influx auth create --read-buckets --read-checks --read-dashboards --read-dbrps --read-notificationEndpoints --read-notificationRules --read-orgs --read-tasks --read-telegrafs --read-user --write-buckets --write-checks --write-dashboards --write-dbrps --write-notificationEndpoints --write-notificationRules --write-orgs --write-tasks --write-telegrafs --write-user --org test-org --token test-token --json --hide-headers)
          AUTHTOKEN="${AUTHTOKEN//'%'/'%25'}"
          AUTHTOKEN="${AUTHTOKEN//$'\n'/'%0A'}"
          AUTHTOKEN="${AUTHTOKEN//$'\r'/'%0D'}"
          echo "::set-output name=AUTHTOKEN::$AUTHTOKEN"
          sudo influx org list --token test-token
          sudo influx bucket list --token test-token
          sudo influx auth list --user test-user --token test-token --org test-org

      - name: Run local tests (Linux)
        if: startsWith(runner.OS, 'linux')
        env:
          INFLUXDB2: true
          AUTHTOKEN: ${{ steps.influxdb2.outputs.AUTHTOKEN }}
        run: npm test
  #      - name: Run unit tests
  #        run: npm run test:unit
  #      - name: Run integration tests # (linux/osx)
  #        if: startsWith(runner.OS, 'windows') == false
  #        run: DEBUG=testing:* npm run test:integration
  #      - name: Run integration tests # (windows)
  #        if: startsWith(runner.OS, 'windows')
  #        run: set DEBUG=testing:* & npm run test:integration

  # Deploys the final package to NPM
  deploy:
    needs: [adapter-tests-influxdb1,adapter-tests-influxdb2]

    # Trigger this step only when a commit on master is tagged with a version number
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract the version and commit body from the tag
        id: extract_release
        # The body may be multiline, therefore we need to escape some characters
        run: |
          VERSION="${{ github.ref }}"
          VERSION=${VERSION##*/}
          VERSION=${VERSION##*v}
          echo "::set-output name=VERSION::$VERSION"
          BODY=$(git show -s --format=%b)
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=BODY::$BODY"

      - name: Install Dependencies
        run: npm ci

#      - name: Create a clean build
#        run: npm run build
      - name: Publish package to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm whoami
          npm publish

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.extract_release.outputs.VERSION }}
          draft: false
          # Prerelease versions create prereleases on Github
          prerelease: ${{ contains(steps.extract_release.outputs.VERSION, '-') }}
          body: ${{ steps.extract_release.outputs.BODY }}

      - name: Notify Sentry.io about the release
        run: |
          npm i -g @sentry/cli
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          export SENTRY_URL=https://sentry.iobroker.net
          export SENTRY_ORG=iobroker
          export SENTRY_PROJECT=iobroker-influxdb
          export SENTRY_VERSION=iobroker.influxdb@${{ steps.extract_release.outputs.VERSION }}
          sentry-cli releases new $SENTRY_VERSION
          sentry-cli releases set-commits $SENTRY_VERSION --auto
          sentry-cli releases finalize $SENTRY_VERSION

        # Add the following line BEFORE finalize if sourcemap uploads are needed
        # sentry-cli releases files $SENTRY_VERSION upload-sourcemaps build/
